// Code generated by github.com/cshum/vipsgen from libvips 8.16.1; DO NOT EDIT.

package vips

// #include <stdint.h>
import "C"
import (
	"io"
	"reflect"
	"runtime/cgo"
	"unsafe"
)

//export goLoggingHandler
func goLoggingHandler(domain *C.char, level C.int, message *C.char) {
	log(C.GoString(domain), LogLevel(level), C.GoString(message))
}

//export goSourceRead
func goSourceRead(
	handle C.uintptr_t, buffer unsafe.Pointer, size C.longlong,
) C.longlong {
	source, ok := cgo.Handle(handle).Value().(*Source)
	if !ok {
		return -1
	}
	sh := &reflect.SliceHeader{
		Data: uintptr(buffer),
		Len:  int(size),
		Cap:  int(size),
	}
	buf := *(*[]byte)(unsafe.Pointer(sh))
	n, err := source.reader.Read(buf)
	if err == io.EOF {
		return C.longlong(n)
	} else if err != nil {
		return -1
	}
	return C.longlong(n)
}

//export goSourceSeek
func goSourceSeek(
	handle C.uintptr_t, offset C.longlong, whence int,
) C.longlong {
	source, ok := cgo.Handle(handle).Value().(*Source)
	if ok && source.seeker != nil {
		switch whence {
		case io.SeekStart, io.SeekCurrent, io.SeekEnd:
			if n, err := source.seeker.Seek(int64(offset), whence); err == nil {
				return C.longlong(n)
			}
		}
	}
	return -1
}

//export goTargetWrite
func goTargetWrite(
	handle C.uintptr_t, buffer unsafe.Pointer, size C.longlong,
) C.longlong {
	target, ok := cgo.Handle(handle).Value().(*Target)
	if !ok {
		return -1
	}
	sh := &reflect.SliceHeader{
		Data: uintptr(buffer),
		Len:  int(size),
		Cap:  int(size),
	}
	buf := *(*[]byte)(unsafe.Pointer(sh))
	n, err := target.writer.Write(buf)
	if err != nil {
		return -1
	}
	return C.longlong(n)
}

//export goTargetSeek
func goTargetSeek(
	handle C.uintptr_t, offset C.longlong, whence int,
) C.longlong {
	target, ok := cgo.Handle(handle).Value().(*Target)
	if ok && target.seeker != nil {
		switch whence {
		case io.SeekStart, io.SeekCurrent, io.SeekEnd:
			if n, err := target.seeker.Seek(int64(offset), whence); err == nil {
				return C.longlong(n)
			}
		}
	}
	return -1
}
