// Code generated by github.com/cshum/vipsgen from libvips 8.16.1; DO NOT EDIT.

package vips

import "C"
import (
	"github.com/cshum/vipsgen/pointer"
	"io"
	"reflect"
	"unsafe"
)

//export goLoggingHandler
func goLoggingHandler(domain *C.char, level C.int, message *C.char) {
	log(C.GoString(domain), LogLevel(level), C.GoString(message))
}

// Source/Target callbacks acquire the matching Source/Target lock before
// touching reader/writer/seeker fields, returning -1 (read/write error)
// when a concurrent Close has already nil'd the field. Source.Close /
// Target.Close hold the same lock through their s.reader = nil /
// t.writer = nil writes, so libvips never observes torn state.

//export goSourceRead
func goSourceRead(
	ptr unsafe.Pointer, buffer unsafe.Pointer, size C.longlong,
) C.longlong {
	source, ok := pointer.Restore(ptr).(*Source)
	if !ok {
		return -1
	}
	source.lock.Lock()
	defer source.lock.Unlock()
	if source.reader == nil {
		return -1
	}
	sh := &reflect.SliceHeader{
		Data: uintptr(buffer),
		Len:  int(size),
		Cap:  int(size),
	}
	buf := *(*[]byte)(unsafe.Pointer(sh))
	n, err := source.reader.Read(buf)
	if err == io.EOF {
		return C.longlong(n)
	} else if err != nil {
		return -1
	}
	return C.longlong(n)
}

//export goSourceSeek
func goSourceSeek(
	ptr unsafe.Pointer, offset C.longlong, whence int,
) C.longlong {
	source, ok := pointer.Restore(ptr).(*Source)
	if !ok {
		return -1
	}
	source.lock.Lock()
	defer source.lock.Unlock()
	if source.seeker == nil {
		return -1
	}
	switch whence {
	case io.SeekStart, io.SeekCurrent, io.SeekEnd:
		if n, err := source.seeker.Seek(int64(offset), whence); err == nil {
			return C.longlong(n)
		}
	}
	return -1
}

//export goTargetWrite
func goTargetWrite(
	ptr unsafe.Pointer, buffer unsafe.Pointer, size C.longlong,
) C.longlong {
	target, ok := pointer.Restore(ptr).(*Target)
	if !ok {
		return -1
	}
	target.lock.Lock()
	defer target.lock.Unlock()
	if target.writer == nil {
		return -1
	}
	sh := &reflect.SliceHeader{
		Data: uintptr(buffer),
		Len:  int(size),
		Cap:  int(size),
	}
	buf := *(*[]byte)(unsafe.Pointer(sh))
	n, err := target.writer.Write(buf)
	if err != nil {
		return -1
	}
	return C.longlong(n)
}

//export goTargetSeek
func goTargetSeek(
	ptr unsafe.Pointer, offset C.longlong, whence int,
) C.longlong {
	target, ok := pointer.Restore(ptr).(*Target)
	if !ok {
		return -1
	}
	target.lock.Lock()
	defer target.lock.Unlock()
	if target.seeker == nil {
		return -1
	}
	switch whence {
	case io.SeekStart, io.SeekCurrent, io.SeekEnd:
		if n, err := target.seeker.Seek(int64(offset), whence); err == nil {
			return C.longlong(n)
		}
	}
	return -1
}
