//go:build race

// Code generated by github.com/cshum/vipsgen from libvips 8.16.1; DO NOT EDIT.

package vips

import (
	"bytes"
	"image"
	"image/color"
	"image/jpeg"
	"io"
	"sync"
	"testing"
)

func withSingleThreadedVips(t *testing.T) {
	t.Helper()
	prev := raceTestSetConcurrency(1)
	t.Cleanup(func() { raceTestSetConcurrency(prev) })
}

func TestSource_CloseCallbackRace(t *testing.T) {
	withSingleThreadedVips(t)
	data := makeConnectionRaceJPEG(t, 800, 600)

	workers := 16
	const perWorker = 50

	var wg sync.WaitGroup
	wg.Add(workers)
	for range workers {
		go func() {
			defer wg.Done()
			for range perWorker {
				src := NewSource(io.NopCloser(connectionRaceReader{r: bytes.NewReader(data)}))
				im, err := NewImageFromSource(src, nil)
				if err != nil || im == nil {
					src.Close()
					continue
				}
				var out bytes.Buffer
				tgt := NewTarget(connectionRaceWriteCloser{w: &out})
				src.Close()
				_ = im.JpegsaveTarget(tgt, nil)
				tgt.Close()
				im.Close()
			}
		}()
	}
	wg.Wait()
}

func TestTarget_CloseCallbackWriteRace(t *testing.T) {
	withSingleThreadedVips(t)
	data := makeConnectionRaceJPEG(t, 800, 600)

	workers := 16
	const perWorker = 50

	var wg sync.WaitGroup
	wg.Add(workers)
	for range workers {
		go func() {
			defer wg.Done()
			for range perWorker {
				src := NewSource(io.NopCloser(connectionRaceReader{r: bytes.NewReader(data)}))
				im, err := NewThumbnailSource(src, 100, nil)
				if err != nil || im == nil {
					src.Close()
					continue
				}
				var out bytes.Buffer
				tgt := NewTarget(connectionRaceWriteCloser{w: &out})
				_ = im.JpegsaveTarget(tgt, nil)
				tgt.Close()
				im.Close()
				src.Close()
			}
		}()
	}
	wg.Wait()
}

type connectionRaceWriteCloser struct{ w io.Writer }

func (n connectionRaceWriteCloser) Write(p []byte) (int, error) { return n.w.Write(p) }
func (n connectionRaceWriteCloser) Close() error                { return nil }

type connectionRaceReader struct{ r io.Reader }

func (c connectionRaceReader) Read(p []byte) (int, error) { return c.r.Read(p) }

func makeConnectionRaceJPEG(t *testing.T, w, h int) []byte {
	t.Helper()
	img := image.NewRGBA(image.Rect(0, 0, w, h))
	for y := range h {
		for x := range w {
			img.Set(x, y, color.RGBA{
				R: uint8((x * 7) % 256),
				G: uint8((y * 13) % 256),
				B: uint8(((x + y) * 3) % 256),
				A: 255,
			})
		}
	}
	var buf bytes.Buffer
	if err := jpeg.Encode(&buf, img, &jpeg.Options{Quality: 80}); err != nil {
		t.Fatalf("jpeg.Encode: %v", err)
	}
	return buf.Bytes()
}
