// Code generated by github.com/cshum/vipsgen from libvips 8.18.2; DO NOT EDIT.

package vips

// #include <stdint.h>
// #include "connection.h"
import "C"
import (
	"fmt"
	"io"
	"runtime/cgo"
	"sync"
)

// Source contains a libvips VipsSourceCustom and manages its lifecycle.
type Source struct {
	reader io.ReadCloser
	seeker io.Seeker
	src    *C.VipsSourceCustom
	handle cgo.Handle
	lock   sync.Mutex
}

// NewSource creates Source from reader
func NewSource(reader io.ReadCloser) *Source {
	Startup(nil)
	s := &Source{reader: reader}
	s.handle = cgo.NewHandle(s)
	seeker, ok := reader.(io.Seeker)
	if ok {
		s.seeker = seeker
		s.src = C.create_go_custom_source_with_seek(C.uintptr_t(s.handle))
	} else {
		s.src = C.create_go_custom_source(C.uintptr_t(s.handle))
	}
	return s
}

// Close source
func (s *Source) Close() {
	if s == nil {
		return
	}
	s.lock.Lock()
	if s.handle != 0 {
		C.clear_source(&s.src)
		s.handle.Delete()
		s.handle = 0
		s.lock.Unlock()
		if s.reader != nil {
			_ = s.reader.Close()
			s.reader = nil
		}
		log("vipsgen", LogLevelDebug, fmt.Sprintf("closing source %p", s))
	} else {
		s.lock.Unlock()
	}
}

// Target contains a libvips VipsTargetCustom and manages its lifecycle.
type Target struct {
	writer io.WriteCloser
	seeker io.Seeker
	target *C.VipsTargetCustom
	handle cgo.Handle
	lock   sync.Mutex
}

// NewTarget creates Target from writer
func NewTarget(writer io.WriteCloser) *Target {
	Startup(nil)
	t := &Target{writer: writer}
	t.handle = cgo.NewHandle(t)
	seeker, ok := writer.(io.Seeker)
	if ok {
		t.seeker = seeker
		t.target = C.create_go_custom_target_with_seek(C.uintptr_t(t.handle))
	} else {
		t.target = C.create_go_custom_target(C.uintptr_t(t.handle))
	}
	return t
}

// Close target
func (t *Target) Close() {
	if t == nil {
		return
	}
	t.lock.Lock()
	if t.handle != 0 {
		C.clear_target(&t.target)
		t.handle.Delete()
		t.handle = 0
		t.lock.Unlock()
		if t.writer != nil {
			_ = t.writer.Close()
			t.writer = nil
		}
		log("vipsgen", LogLevelDebug, fmt.Sprintf("closing target %p", t))
	} else {
		t.lock.Unlock()
	}
}
