// Code generated by github.com/cshum/vipsgen from libvips 8.18.2; DO NOT EDIT.

package vips

// #include <stdint.h>
// #include "connection.h"
import "C"
import (
	"fmt"
	"io"
	"runtime/cgo"
	"sync"
)

var handleDeletes sync.Map

// Source contains a libvips VipsSourceCustom and manages its lifecycle.
type Source struct {
	reader io.ReadCloser
	seeker io.Seeker
	src    *C.VipsSourceCustom
	handle cgo.Handle
	lock   sync.Mutex
}

func newSourceHandle(source *Source) cgo.Handle {
	handle := cgo.NewHandle(source)
	handleDeletes.Store(uintptr(handle), handle)
	return handle
}

func restoreSource(handle C.uintptr_t) (*Source, bool) {
	ctx, ok := cgo.Handle(handle).Value().(*Source)
	if !ok {
		return nil, false
	}
	return ctx, true
}

func deleteSourceHandle(handle cgo.Handle) {
	if handle == 0 {
		return
	}
	if actual, ok := handleDeletes.LoadAndDelete(uintptr(handle)); ok {
		actual.(cgo.Handle).Delete()
	}
}

//export goHandleDelete
func goHandleDelete(handle C.uintptr_t) {
	deleteSourceHandle(cgo.Handle(handle))
}

// NewSource creates Source from reader
func NewSource(reader io.ReadCloser) *Source {
	Startup(nil)
	s := &Source{reader: reader}
	s.handle = newSourceHandle(s)
	seeker, ok := reader.(io.Seeker)
	if ok {
		s.seeker = seeker
		s.src = C.create_go_custom_source_with_seek(C.uintptr_t(uintptr(s.handle)))
	} else {
		s.src = C.create_go_custom_source(C.uintptr_t(uintptr(s.handle)))
	}
	if s.src == nil {
		deleteSourceHandle(s.handle)
		s.handle = 0
	}
	return s
}

// Close source
func (s *Source) Close() {
	if s == nil {
		return
	}
	s.lock.Lock()
	defer s.lock.Unlock()
	if s.src == nil && s.reader == nil && s.handle == 0 {
		return
	}
	reader := s.reader
	s.reader = nil
	s.seeker = nil
	if s.src != nil {
		C.clear_source(&s.src)
	} else {
		deleteSourceHandle(s.handle)
	}
	s.handle = 0
	if reader != nil {
		_ = reader.Close()
	}
	log("vipsgen", LogLevelDebug, fmt.Sprintf("closing source %p", s))
}

// Target contains a libvips VipsTargetCustom and manages its lifecycle.
type Target struct {
	writer io.WriteCloser
	seeker io.Seeker
	target *C.VipsTargetCustom
	handle cgo.Handle
	lock   sync.Mutex
}

func newTargetHandle(target *Target) cgo.Handle {
	handle := cgo.NewHandle(target)
	handleDeletes.Store(uintptr(handle), handle)
	return handle
}

func restoreTarget(handle C.uintptr_t) (*Target, bool) {
	ctx, ok := cgo.Handle(handle).Value().(*Target)
	if !ok {
		return nil, false
	}
	return ctx, true
}

func deleteTargetHandle(handle cgo.Handle) {
	if handle == 0 {
		return
	}
	if actual, ok := handleDeletes.LoadAndDelete(uintptr(handle)); ok {
		actual.(cgo.Handle).Delete()
	}
}

// NewTarget creates Target from writer
func NewTarget(writer io.WriteCloser) *Target {
	Startup(nil)
	t := &Target{writer: writer}
	t.handle = newTargetHandle(t)
	seeker, ok := writer.(io.Seeker)
	if ok {
		t.seeker = seeker
		t.target = C.create_go_custom_target_with_seek(C.uintptr_t(uintptr(t.handle)))
	} else {
		t.target = C.create_go_custom_target(C.uintptr_t(uintptr(t.handle)))
	}
	if t.target == nil {
		deleteTargetHandle(t.handle)
		t.handle = 0
	}
	return t
}

// Close target
func (t *Target) Close() {
	if t == nil {
		return
	}
	t.lock.Lock()
	defer t.lock.Unlock()
	if t.target == nil && t.writer == nil && t.handle == 0 {
		return
	}
	writer := t.writer
	t.writer = nil
	t.seeker = nil
	if t.target != nil {
		C.clear_target(&t.target)
	} else {
		deleteTargetHandle(t.handle)
	}
	t.handle = 0
	if writer != nil {
		_ = writer.Close()
	}
	log("vipsgen", LogLevelDebug, fmt.Sprintf("closing target %p", t))
}
