// Code generated by github.com/cshum/vipsgen from libvips 8.18.2; DO NOT EDIT.

package vips

// #include "connection.h"
import "C"
import (
	"fmt"
	"github.com/cshum/vipsgen/pointer"
	"io"
	"sync"
	"unsafe"
)

// Source contains a libvips VipsSourceCustom and manages its lifecycle.
type Source struct {
	reader io.ReadCloser
	seeker io.Seeker
	src    *C.VipsSourceCustom
	ptr    unsafe.Pointer
	lock   sync.Mutex
}

// NewSource creates Source from reader
func NewSource(reader io.ReadCloser) *Source {
	Startup(nil)
	s := &Source{reader: reader}
	s.ptr = pointer.Save(s)
	seeker, ok := reader.(io.Seeker)
	if ok {
		s.seeker = seeker
		s.src = C.create_go_custom_source_with_seek(s.ptr)
	} else {
		s.src = C.create_go_custom_source(s.ptr)
	}
	return s
}

// Close source
//
// Holds s.lock through the entire teardown (including the s.reader = nil
// write) so it cannot race with goSourceRead, which also takes s.lock
// before reading s.reader. C.clear_source -> g_clear_object only fires
// GLib dispose/finalize handlers, never the registered "read" signal,
// so calling it under the Go lock cannot deadlock against an in-flight
// goSourceRead callback.
func (s *Source) Close() {
	if s == nil {
		return
	}
	s.lock.Lock()
	defer s.lock.Unlock()
	if s.ptr == nil {
		return
	}
	C.clear_source(&s.src)
	pointer.Unref(s.ptr)
	s.ptr = nil
	if s.reader != nil {
		_ = s.reader.Close()
		s.reader = nil
	}
	log("vipsgen", LogLevelDebug, fmt.Sprintf("closing source %p", s))
}

// Target contains a libvips VipsTargetCustom and manages its lifecycle.
type Target struct {
	writer io.WriteCloser
	seeker io.Seeker
	target *C.VipsTargetCustom
	ptr    unsafe.Pointer
	lock   sync.Mutex
}

// NewTarget creates Target from writer
func NewTarget(writer io.WriteCloser) *Target {
	Startup(nil)
	t := &Target{writer: writer}
	t.ptr = pointer.Save(t)
	seeker, ok := writer.(io.Seeker)
	if ok {
		t.seeker = seeker
		t.target = C.create_go_custom_target_with_seek(t.ptr)
	} else {
		t.target = C.create_go_custom_target(t.ptr)
	}
	return t
}

// Close target
//
// Symmetric fix to Source.Close: holds t.lock through t.writer = nil so
// it cannot race with goTargetWrite, which also takes t.lock before
// reading t.writer.
func (t *Target) Close() {
	if t == nil {
		return
	}
	t.lock.Lock()
	defer t.lock.Unlock()
	if t.ptr == nil {
		return
	}
	C.clear_target(&t.target)
	pointer.Unref(t.ptr)
	t.ptr = nil
	if t.writer != nil {
		_ = t.writer.Close()
		t.writer = nil
	}
	log("vipsgen", LogLevelDebug, fmt.Sprintf("closing target %p", t))
}
