//go:build race

// Code generated by github.com/cshum/vipsgen from libvips 8.18.2; DO NOT EDIT.

package vips

// #cgo pkg-config: vips
// #include "util.h"
import "C"

func raceTestSetConcurrency(n int) int {
	prev := int(C.vips_concurrency_get())
	C.vips_concurrency_set(C.int(n))
	return prev
}
