// Code generated by github.com/cshum/vipsgen. DO NOT EDIT.

package vips

// #include "connection.h"
import "C"
import (
	"fmt"
	"github.com/cshum/vipsgen/pointer"
	"io"
	"sync"
	"unsafe"
)

// Source contains a libvips VipsSourceCustom and manages its lifecycle.
type Source struct {
	reader io.ReadCloser
	seeker io.Seeker
	src    *C.VipsSourceCustom
	ptr    unsafe.Pointer
	lock   sync.Mutex
}

// NewSource creates Source from reader
func NewSource(reader io.ReadCloser) *Source {
	Startup(nil)
	s := &Source{reader: reader}
	seeker, ok := reader.(io.ReadSeeker)
	if ok {
		s.seeker = seeker
		s.ptr = pointer.Save(s)
		s.src = C.create_go_custom_source_with_seek(s.ptr)
	} else {
		s.ptr = pointer.Save(s)
		s.src = C.create_go_custom_source(s.ptr)
	}
	return s
}

// Close source
func (s *Source) Close() {
	if s == nil {
		return
	}
	s.lock.Lock()
	if s.ptr != nil {
		C.clear_source(&s.src)
		pointer.Unref(s.ptr)
		s.ptr = nil
		s.lock.Unlock()

		if s.reader != nil {
			_ = s.reader.Close()
		}
		log("vipsgen", LogLevelDebug, fmt.Sprintf("closing source %p", s))
	} else {
		s.lock.Unlock()
	}
}
